### ISSUE TITLE
[Question] NoClassDefFoundError after upgrade firebase to 10.7.0

### ISSUE THREAD

**Issue by mrerenimo** [firebase/firebase-unity-sdk#688]
* Unity editor version: 2021.3.20f
  * Firebase Unity SDK version: 10.7.0
  * Other Firebase Components in use: Auth , Database (10.7.0 all)
  * Additional SDKs you are using: OneSignal
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

After upgrading my Firebase version to 10.7.0 and adding OneSignal to my project there was conflicts messages when resolving by Android Resolver and resolve failed.  I upgraded my Google Play Service to lastest version which is 0.11.01 and change the GooglePlayGamesDependencies.xml repo to right destination, it solved but i always get this warnings. 

![image](https://user-images.githubusercontent.com/94186422/235177439-7eafbc04-400d-49c7-a592-b34d82a0bdca.png)

App crashes and getting this errors when running.

![image](https://user-images.githubusercontent.com/94186422/235177924-c1c87045-f094-418b-a521-3ed61fb43375.png)

**Comment by mrerenimo** [comment]
> Hi @mrerenimo,
> 
> Thanks for reporting this. I wasn't successful in my initial attempt to reproduce your issue. Could you provide more detailed steps on how to replicate the behavior you're facing so we can identify what's causing this?

In my main branch i use :
Firebase 9.3.0
 External Dependency Manager version 1.2.172. 
 Google play service 0.10.13
 
 I create a new branch :
 Firabe  10.7.0.
 External Dependency Manager 1.2.175
 Google play service 0.11.01 (even if i don't update this. I got same errors)
 One Signal 3.0.10
 
and when i try to resolve, it says resolve conflicts in my new branch but main branch works normal. (Because of that I upgrade my GPS) There are always conflicts and says succesfully done. But when i'm run on a device. It's crash instantly.

**Comment by paulinon** [comment]
Hi @mrerenimo,

Could you try if enabling both `Custom Main Gradle Template` and `Custom Gradle Properties Template` from your Player Settings makes any difference? If not, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that this could be used as a baseline for troubleshooting.

**Comment by mrerenimo** [comment]
I found the solution. One of my plugin makes conflict on dependencies on gpgs-support. I enabled Custom Main Gradle Template and Custom Gradle Properties Template.
It helps me also :
https://www.youtube.com/watch?v=LQKWcCBQyMo
