### ISSUE TITLE
[Bug] Google.MiniJSON.dll conflicts with Unity package MiniJSON

### ISSUE THREAD

**Issue by serioushen** [firebase/firebase-unity-sdk#306]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.0f1
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Crashlytics
  * Additional SDKs you are using:
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS / Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

After updating from Firebase 8.9.0 to 8.10.1, we're now getting a conflict in namespace for type Json between Firebase's included Google.MiniJSON.dll and the MiniJSON package we include via Package Manager:

`error CS0433: The type 'Json' exists in both 'Google.MiniJson, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'MiniJSON, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`
 
It appears that the MiniJSON package has now been included in Firebase's Google.MiniJSON.dll in Firebase 8.10?  
As this causes a conflict, would it be possible for you to wrap Firebase's Json in its own namespace to avoid conflicts with the MiniJSON package?

**Comment by a-maurice** [comment]
Interesting. Do you have a link to the other MiniJSON package you are using?

**Comment by serioushen** [comment]
Yes, here's the link to MiniJSON package.
https://gist.github.com/darktable/1411710

Our project worked fine in Firebase 8.9.0, but cannot upgrade to 8.10.1 since we now have many type Json conflicts.  To avoid name conflicts, I think such public libraries should be in Firebase's own namespace if you include them.

**Comment by a-maurice** [comment]
Ah yes, we've figured out the problem is indeed the custom namespace we were using got lost in the transition between built infrastructures. We will work on getting a fix out, but in the meantime as a workaround you could replace the Google.MiniJson.dll file with the version that was in 8.9.0 (or older releases), which can be downloaded at https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_8.9.0.zip

**Comment by StephenHodgson** [comment]
Might as well just add dependency on unity's newtonsoft package and purge any extra work on this side to keep it updated.

**Comment by Nyankoo** [comment]
Still an issue in 9.0.0

**Comment by a-maurice** [comment]
The Firebase for Unity SDK v9.1.0 is out, which should have the bitcode enabled correctly in the library. It can be downloaded from here https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.1.0

Thanks again for flagging this issue.
